name: "Rust crypto-dev environment"
description: "A GitHub Action that makes setting up crypto-related workflow environments easy"
author: "Thomas Braun <thomas.braun@avarok.net>"

runs:
  using: "composite"
  steps:
    - name: Install LLVM and Clang
      if: startsWith(runner.os, 'windows')
      uses: KyleMayes/install-llvm-action@v1.5.1
      with:
        version: "13.0"
        directory: ${{ runner.temp }}/llvm

    - name: Set LIBCLANG_PATH
      if: startsWith(runner.os, 'windows')
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      shell: cmd

    - name: Install OpenSSL
      if: startsWith(runner.os, 'windows')
      run: |
        # Define the URL of the raw script file
        $scriptUrl = "https://github.com/ilia-shipitsin/runner-images/blob/b0381c354e34a74b8a62cc07ffbcbddae01a0ca0/images/win/scripts/Installers/Install-OpenSSL.ps1"

        # Specify the path to save the script locally
        $localScriptPath = "C:\Install-OpenSSL.ps1"

        # Download the script from the server
        Invoke-WebRequest -Uri $scriptUrl -OutFile $localScriptPath

        # Execute the downloaded script
        # You might need to change the execution policy temporarily if it's restricted
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

        # Run the script
        & $localScriptPath
      shell: powershell

    - name: Set OPENSSL_ROOT_DIR
      if: startsWith(runner.os, 'windows')
      run: echo "OPENSSL_ROOT_DIR=C:/Program Files/OpenSSL" >> $env:GITHUB_ENV
      shell: cmd

    - name: Set OPENSSL_ROOT_DIR
      if: startsWith(runner.os, 'macos')
      run: echo "OPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1" >> $GITHUB_ENV
      shell: bash

    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --force cargo-make

